#
_target_: src.modules.BPClassification.execute_tasks
 #${trainer}
trainer: 
  _target_: src.modules.BPClassification.BP_Trainer
  config: ${_run}
tasks:
  - _target_: src.modules.BPClassification.call_train
    trainer: #${trainer}
  - _target_: src.modules.BPClassification.call_test
    trainer: #${trainer}