_target_: src.models.se_resnet1d.resnet18
# pretrained: true
num_classes: 2
# input_size: [1,1250]
in_channels: 1
dropout: 0.5
first_layer_kernel_size: 7
first_layer_channels: 64
layer_size_multiplier: [1, 1, 2, 2]
# use_fc: true
# use_bn: true

