defaults:
  - /model/vit
  - /data/BPDataset
  - /network/base_network
  - _self_
data:
  train_dataset:
    data_len: -1
  val_dataset:
    data_len: -1
  test_dataset:
    data_len: -1
model:
  dim: 96
network:
  batch_size: 64
  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4
    weight_decay: 0
  scheduler:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
  ckpt_path: checkpoints/resnet/0425_vit_3
  early_stopping: 
    patience: 4
  resume: false

