# for sweep 
defaults:
  - /model/resnet18
  - /data/BPDataset
  - /network/base_network
  - _self_
data:
  train_dataset:
    data_len: -1
  val_dataset:
    data_len: -1
  test_dataset:
    data_len: -1
    
model:
  _target_: src.models.se_resnet1d.se_resnet18mini
  first_layer_channels: 64
  layer_size_multiplier: [1, 1, 2, 4]
network:
  no_warning: True
  batch_size: 64
  fold: 1
  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4
    weight_decay: 0
  scheduler:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
  ckpt_path: checkpoints/resnet/0429_sweep
  early_stopping: 
    patience: 4
  resume: false

